### ISSUE TITLE
Unhandled exception - /home .

### ISSUE THREAD

**Issue by HarbourHeading** [LapisPlugins/HomeSpawn#10]
When making a home with . and I am guessing other things that are not numbers and letters, an unhandled exception appears.
Pastebin: https://pastebin.com/rGy1susM

**Comment by Dart2112** [comment]
That should happen with any home name that isn't a valid pathname in YAML
I can make a fix for it but it's not going to be a priority

**Comment by Dart2112** [comment]
Issue fixed in the new version. 

Sorry for the delay on this one, took longer to look at than it really should have
