### ISSUE TITLE
Deleting homes from players on my MC Server

### ISSUE THREAD

**Issue by OnThySpot** [LapisPlugins/HomeSpawn#11]
Hi,
I am hosting this small Minecraft server for a couple of my friends and I am using the HomeSpawn plugin via Spigot. I am hosting using APEX Hosting.
I want to monitor which "homes" they all are setting up and even possibly want to delete the certain ones that they have.
I have found a way to view their home list, but not yet how to delete one if I want to.
I am now using /homespawn player [username] to get the data and I know how to tp to their homes, but is there even a way to delete them?

As you might already have seen from my poor writing capabilities, I am not a native English speaker, nor an actual programmer myself. Big chance here that I am just missing out on some basic knowledge.
Hope you can help me with this.

**Comment by Dart2112** [comment]
Deleting another player's home is not something that you can do with a command.
But it can be done manually by editing the config files.
If you find a home you wish to delete you can have a look in the homespawn folder on your server and you will see a player data folder. In that folder is a .yml folder for each UUID of a player. You can use a website like https://mcuuid.net to convert a username to a UUID, this will allow you to find the file for any players username.
Inside the players file you will see a list under the heading "Homes:"
Each line represents a home, with the part before the ":" being the home name and the part after being the location of the home.
Here you can remove the whole line for the home that you want to remove. This will remove that player's ability to use that home.

If you have any questions about this, feel free to comment again and ask them.

**Comment by OnThySpot** [comment]
Thank you so much for the amazingly clear answer!
And also for the provided website to unscramble the usernames from UUID to their regular usernames.

**Comment by OnThySpot** [comment]
Thank you so much for the amazingly clear answer!
And also for the provided website to unscramble the usernames from UUID to their regular usernames.
