### ISSUE TITLE
Add option to disable config watcher

### ISSUE THREAD

**Issue by timmyRS** [LapisPlugins/HomeSpawn#3]
Checking for file changes every second isn't useful when a server is running 24/7, so please add an option to disable that.

**Comment by Dart2112** [comment]
It doesn't check every second. it actually waits for the system to tell it if a file has been changed in the correct folder before it checks to see if it needs to be reloaded. I see no reason to disable this as it runs on its own thread and is idle most of the time, but I will add it in the next update. The next update will come when a bug or significant new feature is added so don't expect it immediately.

**Comment by timmyRS** [comment]
Every plugin simply has a command to reload the config and your async thread also breaks reloading.

**Comment by Dart2112** [comment]
I understand that it has a reload command, but it doesn't make sense to reload all the files when only a config has changed. Also what problems are you having with reloading? There is a system in place to kill the thread when the plugin gets disabled like in a server stop or reload.

**Comment by timmyRS** [comment]
Whenever I run `/reload`, Spigot prints this:

> Nag author: 'Dart2112' of 'HomeSpawn' about the following: This plugin is not properly shutting down its async tasks when it is being reloaded.  This may cause conflicts with the newly loaded version of the plugin

I'd highly appreciate a simple `/homespawn reload` command and an option to disable file watchers. Cheers.

**Comment by Dart2112** [comment]
There is already a reload command and like I said I will add an option to disable the file watcher in the next update, I have also added the method call to the on disable to deal with the watcher not stopping

**Comment by Dart2112** [comment]
this has been done in the latest update
