### ISSUE TITLE
homespawn player don't work

### ISSUE THREAD

**Issue by Gerolfing** [LapisPlugins/HomeSpawn#5]
/homespawn player don't work as intended. It shows homes only if player is online but you still can't teleport to it nor see it's coordinates. And for offline players it just shows that they don't have any homes.

Also it would be cool to be able to see coordinates of other player's homes without teleportation. like on screenshot below. And commands for moderators to set/delete other player's homes.
![2019-08-28_02 07 14](https://user-images.githubusercontent.com/23654416/63813897-a6c7b180-c937-11e9-8202-7df550e42522.png)

**Comment by Dart2112** [comment]
Would you be able to check the jar file in Issue #6 and see if the error still occurs
I will look into your suggestions

**Comment by Gerolfing** [comment]
I have checked it and it seems bug remains, but now it shows offline player's homes,but still can't teleport. I checed homes for player Balgruuf but after click it changes nick to Balgruuf2....
![2019-09-07_15 03 29](https://user-images.githubusercontent.com/23654416/64474657-84783400-d180-11e9-982e-2759b1449c6f.png)
![2019-09-07_15 03 47](https://user-images.githubusercontent.com/23654416/64474658-84783400-d180-11e9-83c7-fe508b84456a.png)

**Comment by Dart2112** [comment]
Referenced commit fixes this issue, it wasn't putting a space in the command it ran so it wouldn't work. Pushing out an update now
