### ISSUE TITLE
An internal error occurred while attempting to perform the command.

### ISSUE THREAD

**Issue by Darkstar98** [LapisPlugins/HomeSpawn#6]
Today, a player on my server began having an issue with Homespawn. Whenever they try to use any homespawn command relating to them, or if I do /homespawn player <playername> on them, a massive number of errors appear, so many that I cannot see the entire stack trace in the console. No other player has the issue, and the owner of the server is currently looking into it. 

![Screenshot (10)](https://user-images.githubusercontent.com/50161544/64393058-b3c26000-d01d-11e9-88ea-4995bdce6b33.png)

**Comment by Dart2112** [comment]
Right, this is an issue with world error detection. basically one of that player's homes is in a world that doesn't exist anymore, so it tries to delete the home but the player isn't loaded yet so it makes an infinite loop of loading the player's data and trying to delete the home. I've made a fix that I will push now, I'll send a jar file with that patch soon.

**Comment by Dart2112** [comment]
[Homespawn.zip](https://github.com/LapisPlugins/HomeSpawn/files/3581956/Homespawn.zip)
I'll push out an update when I get home, but this will fix the issue.
