### ISSUE TITLE
Disable in certain worlds

### ISSUE THREAD

**Issue by TomSipsOnCurry** [LapisPlugins/HomeSpawn#9]
suggestion 1: Add the ability to disable the plugins in certain worlds

suggestion 2: Fix the bug where people can go to other people's bases with /home <Player name>

**Comment by Dart2112** [comment]
> suggestion 2: Fix the bug where people can go to other people's bases with /home

That's not an issue that's been reported before, you're gonna need to explain that one

**Comment by TomSipsOnCurry** [comment]
I'm sorry, that was false information from one of my members, but could you please add the feature to disable in certain worlds?
